package com.ogborn.c868final.Model;

/**
 * describes contact object and its methods
 */
public class Contact {
    //<editor-fold desc="data members">
    /**
     * unique identifier for the contact
     */
    private int contactID;

    /**
     * name of the contact
     */
    private String contactName;

    /**
     * email address of the contact
     */
    private String email;
    //</editor-fold>

    /**
     * constructor for contact objects
     * @param contactID the contact id. should be autogenerated by the database
     * @param contactName the name of the contact
     * @param email the contact's email
     */
    public Contact(int contactID, String contactName, String email) {
        this.contactID = contactID;
        this.contactName = contactName;
        this.email = email;
    }

    /**
     * gets the contact id for a contact
     * @return the contact id
     */
    public int getContactId() {
        return contactID;
    }

    /**
     * gets the contact name
     * @return the contact name
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * gets the contact email
     * @return the contact email
     */
    public String getEmail() {
        return email;
    }

    /**
     * sets the contact id. should be unused
     * @param contactID the contact id to set
     */
    public void setContactID(int contactID) {
        this.contactID = contactID;
    }

    /**
     * sets the contact name. should be unused
     * @param contactName te contact name to set
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * sets the contact email. should be unused.
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * exports the contact name for use in a dropdown
     * if we don't implement a toString() then our combobox will show junk
     * @return the contact name
     */
    @Override
    public String toString() {
        return contactName;
    }
}
